### ISSUE TITLE
rm -rf each time the machine starts?

### ISSUE THREAD

**Issue by maxgalbu** [nurelm/spree_vagrant#5]
why there's this line on the boostrap.sh:

``` bash
su - vagrant -c "rm -rf /vagrant/spree"
su - vagrant -c "mkdir -p /vagrant/$SPREE_FOLDER"
```

Doesn't this delete the whole folder and recreate it afterwards? Does this mean that every change I make is lost after reboot?

**Comment by MisinformedDNA** [comment]
From http://docs.vagrantup.com/v2/provisioning/basic_usage.html:

> By default, provisioners are only run once, during the first vagrant up since the last vagrant destroy, unless the --provision flag is set, as noted above.

**Comment by maxgalbu** [comment]
oh right thanks! :)
